### ISSUE TITLE
Issue with cabal installation of quickcheck-unicode. Not in scope shrinkList - ExitFailure 1

### ISSUE THREAD

**Issue by cyril23** [bos/quickcheck-unicode#1]
Hello,
I have successfully installed Quickcheck, but am not able to install quickcheck-unicode.
Here is the output from CMD (Windows 7 64 bit):

C:\Users\ME>cabal install quickcheck-unicode
Resolving dependencies...
Configuring quickcheck-unicode-1.0.0.0...
Building quickcheck-unicode-1.0.0.0...
Failed to install quickcheck-unicode-1.0.0.0
Last 10 lines of the build log ( C:\Users\ME\AppData\Roaming\cabal\log
s\quickcheck-unicode-1.0.0.0.log ):
Building quickcheck-unicode-1.0.0.0...
Preprocessing library quickcheck-unicode-1.0.0.0...
[1 of 1] Compiling Test.QuickCheck.Unicode ( Test\QuickCheck\Unicode.hs, dist\bu
ild\Test\QuickCheck\Unicode.o )

Test\QuickCheck\Unicode.hs:66:31:
    Not in scope: `shrinkList'
    Perhaps you meant one of these:
`shrinkInit' (imported from Test.QuickCheck),
      `shrinking' (imported from Test.QuickCheck)
cabal: Error: some packages failed to install:
quickcheck-unicode-1.0.0.0 failed during the building phase. The exception
was:
ExitFailure 1

C:\Users\ME>

The Logfile ("C:\Users\ME\AppData\Roaming\cabal\logs\quickcheck-unicode-1.0.0.0.log") contains this:

Building quickcheck-unicode-1.0.0.0...
Preprocessing library quickcheck-unicode-1.0.0.0...
[1 of 1] Compiling Test.QuickCheck.Unicode ( Test\QuickCheck\Unicode.hs, dist\build\Test\QuickCheck\Unicode.o )

Test\QuickCheck\Unicode.hs:66:31:
    Not in scope: `shrinkList'
    Perhaps you meant one of these:
`shrinkInit' (imported from Test.QuickCheck),
      `shrinking' (imported from Test.QuickCheck)

By the way cabal --version shows this:
cabal-install version 1.22.0.1
using version 1.22.1.1 of the Cabal library

I am using Haskell Platform, have installed the HaskellPlatform-2014.2.0.0-x86_64-setup.exe. No problems with other packages so far.

**Comment by bos** [comment]
This was a mistake on my part; I had incorrectly identified the lower bound on QuickCheck. I've issued a fix that correctly depends on 2.7 or above.
